### ISSUE TITLE
Plugin nie nadaje się do użytku na serwerach produkcyjnych

### ISSUE THREAD

**Issue by Envqu** [Kamilkime-Plugins/KSafe#10]
Dzień dobry.
Chciałbym tylko wspomnieć o tym, że plugin nie nadaję się tak naprawdę do niczego.
Dokładniej chodzi o bardzo łatwy sposób na kopiowanie itemów przez źle zaimplementowany i totalnie niepotrzebny system przenoszenia itemków na pierwszy lepszy slot.
Dodatkowo fatalna sprawa, perły kopiują się po zabijaniu endermanów? XD

**Comment by Kamilkime** [comment]
No wiesz... Skoro taki błąd w wydanym pluginie jest - znaczy, że nie trafiłem na niego w czasie testów. A jeśli nikt mi nie napisze, że błąd jest - nie mam jak go naprawiać. A o tych rzeczach, o których piszesz - słyszę pierwszy raz :/

1. Mówiąc ` system przenoszenia itemków na pierwszy lepszy slot` - co masz na myśli?
2. Ten błąd z kopiowaniem występuje w jakich sytuacjach - np. przy automatycznym wydawaniu itemów ze schowka?
3. Ten błąd z perłami występuje zawsze jak zabijasz, czy tylko w jakichś konkretnych przypadkach?
4. Jakiej wersji pluginu i wersji MC używasz?

**Comment by Kamilkime** [comment]
Skoro odpowiedzi nie było - rozumiem, że błędu jednak nie ma. W razie gdybyś jednak chciał powiedzieć coś więcej - napisz tutaj lub stwórz nowe issue.

**Comment by Kamilkime** [comment]
Ktoś inny wytłumaczył mi jaki może być problem, teraz powinno już być ok:
https://github.com/Kamilkime-Plugins/KSafe/releases/tag/v1.0.6

Nie wiem czy to o to ci chodziło, może tak
