### ISSUE TITLE
AntyNogi

### ISSUE THREAD

**Issue by grabeq123** [Kamilkime-Plugins/KSafe#3]
Stworz plugin z craftingiem na antynogi. Polega to na tym ze gdy gracz ma w eq i trzyma w reku antynogi czyli np "Zlote buty" + dodaj aby byly enchantowane poprostu aby sie wyróżniały i kliknie prawym przyciskiem myszy to tepa sie do gracza ktory go zatakował. Wazna sprawa jest aby gracz nie mogł załozyć tych antynog do eq i aby dalo sie edytowac crafting bylo lore i nazwe przedmiotu. Fajnie jakby tez bylo w actiobarze ze np uzyles antynog gdy kliknales prawym przyciskiem myszy. Glowne ich zastosowanie to ucieszka z nozek ktore sa robione przez innych graczy. Gdy gracz jakis  robi nogi innemu graczowi czyli jakas budowle stawia tepa tam gracza i ten gracz nie moze uciec to tylko antynogi mu pomoga aby byla sprawiedliwa walka. Jezeli cos jest nie jasne to moze to wyjasnic bardziej

**Comment by grabeq123** [comment]
Fajnie gdyby plugin ten dzialal na 1.8.8 i nie tylko. Plugin ten głownie  sie uzywa na Wojnach gildi z pluginem FG.

**Comment by grabeq123** [comment]
Fajnie byłoby gdyby te antynogi mialy jakies zabezpieczenie zeby nie mozna ich bylo uzywac tak o tylko np jak gracz jest w potrzasku czyli cos mu przeszkadza jakis blok i wtedy go gracz klepie  + Dodaj komende np: /antynogi autocrafting super opcja poniewaz jezeli gracz ma w eq all przedmioty do tego to automatycznie mu kraftuje je  ale dodaj do tego permisje ze tylko gracz z ta permisja ma do tej komendy dostep jezeli juz podejmiesz sie tego projektu ktory wydaje sie fajnym pomyslem :D

**Comment by Kamilkime** [comment]
Jak masz jakieś propozycje na inne pluginy - najlepiej napisz do mnie na discordzie (Kamilkime#9792). Zgłoszenia do KSafe najlepiej niech dotyczą tylko tego pluginu - inaczej się bałagan zrobi
