### ISSUE TITLE
SandFarmer , BoyFarmer , KopaczFosy 

### ISSUE THREAD

**Issue by grabeq123** [Kamilkime-Plugins/KSafe#4]
Mam pomysl na prosty plugin  kazdy z wymienionych przeze mnie rzeczy  sa uzywane rowniez w wojnach gildi najczesciej na 1.8.8 a poniewaz nie ma takiego pluginy ktory to obsługuję tylko skrypty niestety ktorych uzywam ale bardzo ich nie lubie wiec wpadlem na pomysl ktory ci sie moze spodoba . Wszystkie z 3 rzeczy musza miec crafting   np boyfaemer sie craftuje obsem do okola a srodek to kox ale to tylko przyklad ktory mozna bedzie edytowac i dostaje za ten crafting np Boyfarmer   ktory po postawieniu   do bedroka tworzy obsydian a sandfarmer  do bedrocka piasek a kopaczfosy  zostawia dziure pusta ale do bedrocka. Wazne aby wszystkie z 3 rzeczy mozna bylo uzywac tylko i wylacznie na terenie gildi! Aby rowniez przedmioty te czyli boyfarmer , sandfarmer, kopaczfosy mialy enchant zeby sie poprostu wyroznialy posiadaly rowniez lore i name itemu. A w actionbarze takie powiadomienia np Gdy gracz probuje postawic nie na terenie gildi to "Tu nie mozesz postyawic BoyFarmera" oczywiscie edytowalne  lub  Postawiles BoyFarmer! gdy postawi go

**Comment by grabeq123** [comment]
+ dodaj ze kazdy z tych 3 rzeczy rowniez bedzie komenda np /boyfarmer autocrafting gdy gracz ma all itemy w eq i wpisze ta komende to dostanie odrazu  boyfarmer oczywiscie tylko wtedy gdy ma permisje do tej komendy.

**Comment by Kamilkime** [comment]
Jak w https://github.com/Kamilkime/KSafe/issues/3#issuecomment-791974528
