### ISSUE TITLE
Plugin na Sprawdzanie graczy 

### ISSUE THREAD

**Issue by grabeq123** [Kamilkime-Plugins/KSafe#5]
Plugin rowniez bardzo prosty a nigdzie go nie ma a ma bardzo wazne zastosowanie. Polega to na tym ze gdy gracz czituje to trzeba go sprawdzic prawda? Wiec tutaj Administracja potrzbuje pluginu na sprawdzanie gdzie jak wpisza np  /sprawdz <gracz> to tego gracza automatycznie tepa do miejsca gdzie jest sprawdzanie na mapie  a jak bedzie czysty czyli nie bedzie mial czitow to wtedy np /wypusc <gracz> i wtedy tepa gracza z sprawdzarki na spawna. a gdy bedzie mial czity to np /czity <gracz> wtedy banuje gracz z wiadomoscia do suatwienia w configu i rodzajem bana bo np niektorzy chca banowac graczy ktorzy czituja na czas a niektórzy permamentnie wiec ta opcja musiałaby być  do edytowania.  + oczywiscie 2 komendy takie jak /spawnsprawdzania  gdzie po wpisaniu tej komendy bedzie ustawiony resp sprawdzarki i /posprawdzaniu gdzie gracz bedzie tepaty  po sprawdzeniu. Mile byloby widziane dodanie funkcji tez np na Title gdzie jak gracz zostanie przeniesiony To bedzie Pisac Jestes Sprawdzany. Gracz podczas sprawdzania Nie moze miec dostepu do zadnych komend oprocz np /msg  + aby plugin wyslal mu na czasie jakas wiadomosc do suatwienia w configu gdzie ma wejsc aby administracja go sprawdzila. Gdy administracja wpisze /sprawdz <gracza> gracz jak i osoba ktora go bedzie sprawdzac automatycznie sie niech tepna razem do sprawdzarki. A gdy gracz lognie to dostaje automatycznego Bana ktorego tez bedzie mozna sobie skonfigurowac w configu co ma pisac jak lognie i jaki rodzaj bana.

**Comment by Kamilkime** [comment]
Jak w https://github.com/Kamilkime/KSafe/issues/3#issuecomment-791974528
