### ISSUE TITLE
Problem z auto limitem

### ISSUE THREAD

**Issue by kvbvsv** [Kamilkime-Plugins/KSafe#9]
Siemka, mam problem z tym schowkiem/sejfem bo chciałeś sobie użyć ten plugin dodałem na serwer i od razu miałem problem z automatycznym równaniem limitu do schowka/sejfu baza danych mysql podpięta patrzyłem w config wszystko jest git ale nie działa.

**Comment by Kamilkime** [comment]
Jeśli masz OPa lub uprawnienie `ksafe.bypass.supply` - schowek nie dodaje itemów automatycznie
Jeśli masz OPa lub uprawnienie `ksafe.bypass.limit` - schowek nie zabiera itemów automatycznie

**Comment by Kamilkime** [comment]
Więcej pytań już nie było - zakładam więc, że problemem były te uprawnienia
